local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local StarterGui = game:GetService("StarterGui")
local player = Players.LocalPlayer
local mouse = player:GetMouse()
local aimbotEnabled = false

local Rayfield = loadstring(game:HttpGet("https://raw.githubusercontent.com/SiriusSoftwareLtd/Rayfield/refs/heads/main/source.lua"))()
local Window = Rayfield:CreateWindow({
    Name = "Emergency Emden Script (BETA) | By Grok",
    LoadingTitle = "Aimbot Menu",
    LoadingSubtitle = "by Grok",
    ConfigurationSaving = {
        Enabled = false,
        FolderName = nil,
        FileName = "AimbotConfig"
    },
    Discord = {
        Enabled = true,
        Invite = "G7GauBjDxc",
        RememberJoins = true
    },
    KeySystem = true,
    KeySettings = {
        Title = "Key Systems | Grok",
        Subtitle = "Key System | Fin12n",
        Note = "guns.lol/fin12n | Get key here!",
        FileName = "Key",
        SaveKey = true,
        GrabKeyFromSite = false,
        Key = {"ILoveUVG9yaQ=="}
    }
})

local Welcome = Window:CreateTab("Info", 4483362458)
local Main = Window:CreateTab("Main", 4483362458)
local Aimbot = Window:CreateTab("Aimbot (BETA)", 4483362458)

Welcome:CreateLabel("Script v1.0.1")
Welcome:CreateLabel("Script generated by Grok | Edit by Fin12n (Private Script)")
Welcome:CreateLabel("[+] Aimbot Function (BETA)")
Welcome:CreateLabel("[+] Fly (BETA)")

Main:CreateLabel("Fly (BETA)")
Main:CreateButton({
    Name = "Click to Fly!",
    Callback = function()
        local player = game.Players.LocalPlayer
        local character = player.Character or player.CharacterAdded:Wait()
        local rootPart = character:WaitForChild("HumanoidRootPart")
        local humanoid = character:WaitForChild("Humanoid")
        local mouse = player:GetMouse()
        local flying = false
        local speed = 150 -- Tốc độ giống đi bộ trên không
        local bodyVelocity
        local bodyGyro
        
        -- Hàm bật/tắt fly và noclip
        local function toggleFly()
            flying = not flying
            if flying then
                -- Tắt va chạm (noclip)
                for _, part in pairs(character:GetDescendants()) do
                    if part:IsA("BasePart") then
                        part.CanCollide = false
                    end
                end
                
                -- Tạo BodyVelocity và BodyGyro để điều khiển bay
                bodyVelocity = Instance.new("BodyVelocity")
                bodyVelocity.Velocity = Vector3.new(0, 0, 0)
                bodyVelocity.MaxForce = Vector3.new(math.huge, math.huge, math.huge)
                bodyVelocity.Parent = rootPart
                
                bodyGyro = Instance.new("BodyGyro")
                bodyGyro.P = 10000
                bodyGyro.MaxTorque = Vector3.new(math.huge, math.huge, math.huge)
                bodyGyro.Parent = rootPart
                
                humanoid.PlatformStand = true
            else
                -- Tắt fly và noclip
                if bodyVelocity then bodyVelocity:Destroy() end
                if bodyGyro then bodyGyro:Destroy() end
                for _, part in pairs(character:GetDescendants()) do
                    if part:IsA("BasePart") then
                        part.CanCollide = true
                    end
                end
                humanoid.PlatformStand = false
            end
        end
        
        -- Điều khiển hướng bay
        mouse.KeyDown:Connect(function(key)
            if key == "x" then -- Nhấn phím F để bật/tắt fly
                toggleFly()
            end
        end)
        
        -- Cập nhật vị trí khi bay
        game:GetService("RunService").RenderStepped:Connect(function()
            if flying and rootPart then
                local moveDirection = Vector3.new(0, 0, 0)
                
                -- Điều khiển bằng phím WASD và Space/Shift
                if game.UserInputService:IsKeyDown(Enum.KeyCode.W) then
                    moveDirection = moveDirection + (mouse.Hit.LookVector * speed)
                end
                if game.UserInputService:IsKeyDown(Enum.KeyCode.S) then
                    moveDirection = moveDirection - (mouse.Hit.LookVector * speed)
                end
                if game.UserInputService:IsKeyDown(Enum.KeyCode.A) then
                    moveDirection = moveDirection - (mouse.Hit.RightVector * speed)
                end
                if game.UserInputService:IsKeyDown(Enum.KeyCode.D) then
                    moveDirection = moveDirection + (mouse.Hit.RightVector * speed)
                end
                if game.UserInputService:IsKeyDown(Enum.KeyCode.Space) then
                    moveDirection = moveDirection + Vector3.new(0, speed, 0)
                end
                if game.UserInputService:IsKeyDown(Enum.KeyCode.LeftShift) then
                    moveDirection = moveDirection - Vector3.new(0, speed, 0)
                end
                
                -- Cập nhật vận tốc và hướng
                bodyVelocity.Velocity = moveDirection
                bodyGyro.CFrame = mouse.Hit
            end
        end) 
        Rayfield:Notify({
            Title = "Fly Enable!",
            Content = "Press `X` to Fly! again to disable!",
            Duration = 3,
            Image = 4483362458 

        })
    end
})

Aimbot:CreateToggle({
    Name = "Enable Aimbot",
    CurrentValue = false,
    Flag = "AimbotToggle",
    Callback = function(Value)
        aimbotEnabled = Value
        Rayfield:Notify({
            Title = "Aimbot Status",
            Content = aimbotEnabled and "Aimbot Enabled!" or "Aimbot Disabled!",
            Duration = 2,
            Image = 4483362458
        })
    end
})

Tab:CreateLabel("Hold Right Mouse Button to aim")

-- Hàm tìm mục tiêu gần nhất
local function getClosestPlayer()
    local closestPlayer = nil
    local closestDistance = math.huge
    local character = player.Character
    local humanoidRootPart = character and character:FindFirstChild("HumanoidRootPart")

    if not humanoidRootPart then return nil end

    for _, otherPlayer in pairs(Players:GetPlayers()) do
        if otherPlayer ~= player and otherPlayer.Character then
            local targetHumanoid = otherPlayer.Character:FindFirstChild("Humanoid")
            local targetRootPart = otherPlayer.Character:FindFirstChild("HumanoidRootPart")
            if targetHumanoid and targetRootPart and targetHumanoid.Health > 0 then
                local distance = (humanoidRootPart.Position - targetRootPart.Position).Magnitude
                if distance < closestDistance then
                    closestDistance = distance
                    closestPlayer = otherPlayer
                end
            end
        end
    end
    return closestPlayer
end

-- Hàm điều chỉnh camera để khóa mục tiêu
local function aimAt(target)
    local character = player.Character
    local humanoidRootPart = character and character:FindFirstChild("HumanoidRootPart")
    local targetRootPart = target.Character and target.Character:FindFirstChild("Head") -- Khóa vào đầu

    if humanoidRootPart and targetRootPart then
        local camera = workspace.CurrentCamera
        camera.CFrame = CFrame.new(camera.CFrame.Position, targetRootPart.Position)
    end
end

-- Logic aimbot khi giữ phím chuột phải
local aiming = false
UserInputService.InputBegan:Connect(function(input, gameProcessedEvent)
    if input.UserInputType == Enum.UserInputType.MouseButton2 and not gameProcessedEvent then
        aiming = true
    end
end)

UserInputService.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton2 then
        aiming = false
    end
end)

-- Vòng lặp aimbot
RunService.RenderStepped:Connect(function()
    if aimbotEnabled and aiming then
        local closestPlayer = getClosestPlayer()
        if closestPlayer then
            aimAt(closestPlayer)
        end
    end
end)
Aimbot:CreateLabel("Hold Right Mouse Button to aim")
Aimbot:CreateLabel("Funcition in this BETA (So u may Banned) BEWARE!")
Rayfield:Notify({
    Title = "Script Loaded",
    Content = "Script loaded successfully! | Have a Funny time!",
    Duration = 3,
    Image = 4483362458
})
