local Players = game:GetService("Players")
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local StarterGui = game:GetService("StarterGui")
local player = Players.LocalPlayer
local mouse = player:GetMouse()
local aimbotEnabled = false
local fovRadius = 150 -- Bán kính FOV cố định
local aimDelay = 0.1 -- Độ trễ giữa các lần khóa mục tiêu (giây)
local toggleKey = Enum.KeyCode.T -- Phím tắt mặc định để bật/tắt aimbot
local noclipEnabled = false -- Mặc định tắt, bật/tắt bằng phím O
local character = player.Character or player.CharacterAdded:Wait()
local humanoidRootPart = character and character:FindFirstChild("HumanoidRootPart")
local toggleKey = Enum.KeyCode.O -- Phím tắt mặc định là O

local Rayfield = loadstring(game:HttpGet("https://raw.githubusercontent.com/SiriusSoftwareLtd/Rayfield/refs/heads/main/source.lua"))()
local Window = Rayfield:CreateWindow({
    Name = "Emergency Emden Script (BETA) | By Grok",
    LoadingTitle = "Aimbot Menu",
    LoadingSubtitle = "by Grok",
    Theme = "Light",
    ConfigurationSaving = {
        Enabled = false,
        FolderName = nil,
        FileName = "AimbotConfig"
    },
    Discord = {
        Enabled = true,
        Invite = "G7GauBjDxc",
        RememberJoins = true
    },
    KeySystem = true,
    KeySettings = {
        Title = "Key Systems | Grok",
        Subtitle = "Key System | Fin12n",
        Note = "guns.lol/fin12n | Get key here!",
        FileName = "Key",
        SaveKey = true,
        GrabKeyFromSite = false,
        Key = {"ILoveUVG9yaQ=="}
    }
})

local Welcome = Window:CreateTab("Info", 4483362458)
local Main = Window:CreateTab("Main", 4483362458)
local Aimbot = Window:CreateTab("Aimbot (BETA)", 4483362458)

Welcome:CreateLabel("Script v1.0.5")
Welcome:CreateLabel("Script generated by Grok | Edit by Fin12n (Private Script)")
Welcome:CreateLabel("[+] New Aimbot (BETA)")
Welcome:CreateLabel("[+] Fly (Patched)")
Welcome:CreateLabel("[+] Noclip (New) (BETA)")
Welcome:CreateLabel("[+] ESP/Glow (BETA)")

Main:CreateLabel("Fly Function is patched! Please wait")

--Noclip Function
Main:CreateButton({
    Name = "Noclip Function",
    Callback = function()
 -- Đảm bảo script chờ nhân vật được tải
player.CharacterAdded:Connect(function(newCharacter)
    character = newCharacter
    humanoidRootPart = character:WaitForChild("HumanoidRootPart")
    if noclipEnabled then
        enableNoclip()
    end
end)

-- Hàm bật Noclip
local function enableNoclip()
    if humanoidRootPart then
        humanoidRootPart.CanCollide = false
    end
end

-- Hàm tắt Noclip
local function disableNoclip()
    if humanoidRootPart then
        humanoidRootPart.CanCollide = true
    end
end

-- Vòng lặp để duy trì Noclip
RunService.Stepped:Connect(function()
    if noclipEnabled and character and humanoidRootPart then
        humanoidRootPart.CanCollide = false
        -- Di chuyển nhân vật theo hướng di chuyển của người chơi
        local humanoid = character:FindFirstChild("Humanoid")
        if humanoid and humanoid.MoveDirection.Magnitude > 0 then
            humanoidRootPart.Velocity = humanoid.MoveDirection * humanoid.WalkSpeed
            humanoidRootPart.Velocity = Vector3.new(humanoidRootPart.Velocity.X, 0, humanoidRootPart.Velocity.Z)
        else
            humanoidRootPart.Velocity = Vector3.new(0, humanoidRootPart.Velocity.Y, 0)
        end
    end
end)

-- Logic phím tắt để bật/tắt Noclip
UserInputService.InputBegan:Connect(function(input, gameProcessedEvent)
    if input.KeyCode == toggleKey and not gameProcessedEvent then
        noclipEnabled = not noclipEnabled
        if noclipEnabled then
            enableNoclip()
            if StarterGui then
                StarterGui:SetCore("SendNotification", {
                    Title = "Noclip Status",
                    Text = "Noclip Enabled!",
                    Duration = 2
                })
            end
        else
            disableNoclip()
            if StarterGui then
                StarterGui:SetCore("SendNotification", {
                    Title = "Noclip Status",
                    Text = "Noclip Disabled!",
                    Duration = 2
                })
            end
        end
    end
end)
Rayfield:Notify({
    Title = "Noclip Enable!",
    Content = "Press `o` to On | Press again to off",
    Duration = 3,
    Image = 4483362458
})
    end
})

--ESP/Glow
-- Biến để theo dõi trạng thái và lưu trữ
local isEnabled = false
local highlights = {}

-- Hàm thêm Glow và Name Tag
local function addESPToPlayer(player)
    if player.Character then
        local character = player.Character
        local head = character:WaitForChild("Head", 5)
        if head and not highlights[player] then
            -- Thêm Glow
            local highlight = Instance.new("Highlight")
            highlight.Name = "ESPGlow"
            highlight.FillColor = Color3.fromRGB(255, 255, 255)
            highlight.OutlineColor = Color3.fromRGB(255, 255, 255)
            highlight.FillTransparency = 0.3
            highlight.OutlineTransparency = 0
            highlight.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
            highlight.Parent = character

            -- Thêm Name Tag + Khoảng cách
            local billboard = Instance.new("BillboardGui")
            billboard.Name = "ESPName"
            billboard.Size = UDim2.new(0, 150, 0, 40)
            billboard.StudsOffset = Vector3.new(0, 3, 0)
            billboard.AlwaysOnTop = true
            billboard.Parent = head

            local nameLabel = Instance.new("TextLabel")
            nameLabel.Size = UDim2.new(1, 0, 0.5, 0)
            nameLabel.Position = UDim2.new(0, 0, 0, 0)
            nameLabel.BackgroundTransparency = 1
            nameLabel.Text = player.Name
            nameLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
            nameLabel.TextSize = 18
            nameLabel.Font = Enum.Font.SourceSansBold
            nameLabel.TextScaled = false
            nameLabel.Parent = billboard

            local distanceLabel = Instance.new("TextLabel")
            distanceLabel.Size = UDim2.new(1, 0, 0.5, 0)
            distanceLabel.Position = UDim2.new(0, 0, 0.5, 0)
            distanceLabel.BackgroundTransparency = 1
            distanceLabel.Text = "N/A"
            distanceLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
            distanceLabel.TextSize = 14
            distanceLabel.Font = Enum.Font.SourceSans
            distanceLabel.TextScaled = false
            distanceLabel.Parent = billboard

            highlights[player] = { Highlight = highlight, Billboard = billboard, DistanceLabel = distanceLabel }
        end
    end

    -- Xử lý khi nhân vật respawn
    player.CharacterAdded:Connect(function(character)
        local head = character:WaitForChild("Head", 5)
        if head and isEnabled then
            if highlights[player] then
                if highlights[player].Highlight then highlights[player].Highlight:Destroy() end
                if highlights[player].Billboard then highlights[player].Billboard:Destroy() end
            end

            local highlight = Instance.new("Highlight")
            highlight.Name = "ESPGlow"
            highlight.FillColor = Color3.fromRGB(255, 255, 255)
            highlight.OutlineColor = Color3.fromRGB(255, 255, 255)
            highlight.FillTransparency = 0.3
            highlight.OutlineTransparency = 0
            highlight.DepthMode = Enum.HighlightDepthMode.AlwaysOnTop
            highlight.Parent = character

            local billboard = Instance.new("BillboardGui")
            billboard.Name = "ESPName"
            billboard.Size = UDim2.new(0, 150, 0, 40)
            billboard.StudsOffset = Vector3.new(0, 3, 0)
            billboard.AlwaysOnTop = true
            billboard.Parent = head

            local nameLabel = Instance.new("TextLabel")
            nameLabel.Size = UDim2.new(1, 0, 0.5, 0)
            nameLabel.Position = UDim2.new(0, 0, 0, 0)
            nameLabel.BackgroundTransparency = 1
            nameLabel.Text = player.Name
            nameLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
            nameLabel.TextSize = 18
            nameLabel.Font = Enum.Font.SourceSansBold
            nameLabel.TextScaled = false
            nameLabel.Parent = billboard

            local distanceLabel = Instance.new("TextLabel")
            distanceLabel.Size = UDim2.new(1, 0, 0.5, 0)
            distanceLabel.Position = UDim2.new(0, 0, 0.5, 0)
            distanceLabel.BackgroundTransparency = 1
            distanceLabel.Text = "N/A"
            distanceLabel.TextColor3 = Color3.fromRGB(255, 255, 255)
            distanceLabel.TextSize = 14
            distanceLabel.Font = Enum.Font.SourceSans
            distanceLabel.TextScaled = false
            distanceLabel.Parent = billboard

            highlights[player] = { Highlight = highlight, Billboard = billboard, DistanceLabel = distanceLabel }
        end
    end)
end

-- Hàm bật ESP cho tất cả người chơi
local function enableESP()
    for _, player in pairs(game.Players:GetPlayers()) do
        addESPToPlayer(player)
    end
end

-- Hàm tắt ESP
local function disableESP()
    for player, data in pairs(highlights) do
        if data.Highlight then data.Highlight:Destroy() end
        if data.Billboard then data.Billboard:Destroy() end
    end
    highlights = {}
end

-- Cập nhật khoảng cách (sửa lỗi)
local RunService = game:GetService("RunService")
RunService.RenderStepped:Connect(function()
    if isEnabled then
        local localPlayer = game.Players.LocalPlayer
        local localChar = localPlayer.Character
        local localRoot = localChar and localChar:FindFirstChild("HumanoidRootPart")
        if localRoot then
            local localPos = localRoot.Position
            for player, data in pairs(highlights) do
                local character = player.Character
                local targetRoot = character and character:FindFirstChild("HumanoidRootPart")
                if targetRoot then
                    local distance = (localPos - targetRoot.Position).Magnitude
                    data.DistanceLabel.Text = math.floor(distance) .. " studs"
                else
                    data.DistanceLabel.Text = "N/A"
                end
            end
        end
    end
end)

-- Xử lý người chơi mới
game.Players.PlayerAdded:Connect(function(player)
    if isEnabled then
        addESPToPlayer(player)
    end
end)

-- Xử lý người chơi rời game
game.Players.PlayerRemoving:Connect(function(player)
    if highlights[player] then
        if highlights[player].Highlight then highlights[player].Highlight:Destroy() end
        if highlights[player].Billboard then highlights[player].Billboard:Destroy() end
        highlights[player] = nil
    end
end)

-- Nút bật/tắt
Main:CreateButton({
    Name = "Enable/Disable Glow + Nametag",
    Callback = function()
        isEnabled = not isEnabled
        if isEnabled then
            enableESP()
        else
            disableESP()
        end
    end
})

Aimbot:CreateToggle({
    Name = "Enable Aimbot",
    CurrentValue = false,
    Flag = "AimbotToggle",
    Callback = function(Value)
        aimbotEnabled = Value
        Rayfield:Notify({
            Title = "Aimbot Status",
            Content = aimbotEnabled and "Aimbot Enabled!" or "Aimbot Disabled!",
            Duration = 2,
            Image = 4483362458
        })
    end
})

Aimbot:CreateLabel("Hold Right Mouse Button to aim\nPress `T` to Toggle")
Aimbot:CreateLabel("Funcition in this BETA (So u may Banned) BEWARE!")

-- Hàm kiểm tra mục tiêu dưới crosshair (vị trí chuột)
local function getTargetUnderCrosshair()
    local targetPlayer = nil
    local closestDistance = math.huge
    local mousePos = Vector2.new(mouse.X, mouse.Y)

    for _, otherPlayer in pairs(Players:GetPlayers()) do
        if otherPlayer ~= player and otherPlayer.Character then
            local targetHumanoid = otherPlayer.Character:FindFirstChild("Humanoid")
            local targetRootPart = otherPlayer.Character:FindFirstChild("Head")
            if targetHumanoid and targetRootPart and targetHumanoid.Health > 0 then
                local screenPoint, onScreen = workspace.CurrentCamera:WorldToViewportPoint(targetRootPart.Position)
                if onScreen then
                    local targetPos = Vector2.new(screenPoint.X, screenPoint.Y)
                    local distance = (mousePos - targetPos).Magnitude
                    if distance < closestDistance and distance <= fovRadius then
                        closestDistance = distance
                        targetPlayer = otherPlayer
                    end
                end
            end
        end
    end
    return targetPlayer
end

-- Hàm điều chỉnh camera để khóa mục tiêu
local function aimAt(target)
    local character = player.Character
    local humanoidRootPart = character and character:FindFirstChild("HumanoidRootPart")
    local targetRootPart = target.Character and target.Character:FindFirstChild("Head") -- Khóa vào đầu

    if humanoidRootPart and targetRootPart then
        local camera = workspace.CurrentCamera
        camera.CFrame = CFrame.new(camera.CFrame.Position, targetRootPart.Position)
    end
end

-- Logic phím tắt để bật/tắt aimbot
UserInputService.InputBegan:Connect(function(input, gameProcessedEvent)
    if input.KeyCode == toggleKey and not gameProcessedEvent then
        aimbotEnabled = not aimbotEnabled
        Rayfield:Notify({
            Title = "Aimbot Status",
            Content = aimbotEnabled and "Aimbot Enabled!" or "Aimbot Disabled!",
            Duration = 2,
            Image = 4483362458
        })
        -- Đồng bộ trạng thái toggle trong menu
        Rayfield:Set("AimbotToggle", aimbotEnabled)
    end
end)

-- Logic aimbot khi giữ phím chuột phải
local aiming = false
UserInputService.InputBegan:Connect(function(input, gameProcessedEvent)
    if input.UserInputType == Enum.UserInputType.MouseButton2 and not gameProcessedEvent then
        aiming = true
    end
end)

UserInputService.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton2 then
        aiming = false
    end
end)

-- Vòng lặp aimbot (chuyển mục tiêu ngay lập tức theo crosshair)
RunService.RenderStepped:Connect(function()
    if aimbotEnabled and aiming then
        local target = getTargetUnderCrosshair()
        if target then
            aimAt(target)
            wait(aimDelay) -- Thêm độ trễ để trông tự nhiên
        end
    end
end)

Rayfield:Notify({
    Title = "Script Loaded",
    Content = "Script loaded successfully! | Have a Funny time!",
    Duration = 3,
    Image = 4483362458
})
